version: 1
services:
  - type: web
    name: YEGNA_ADMIN
    env: docker
    docker:
      dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-dev
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
